config/routes.rb
Rails.application.routes.draw do

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.save!
		
		redirect_to posts_path
	end

	def index
		@post = Post.all
	end

	private
	def post_params
		params.require(:post).permit(:title, :text, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% if @posts.none? %>
	No posts yet
<% else %>
	<% @posts.each do |post| %>
		<h2><%= post.title %></h2><br>
		<p><%= post.text %></p>
	<% end %>
<% end %>

<%= link_to 'New post', new_post_path %>

app/views/posts/new.html.erb
<h1>Upload an Image</h1>

<%= form_for @post, html: { multipart: true } do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.label :image %>
		<%= f.file_field :image %>

	<p>
		<%= f.submit 'Post it!'%>
	</p>
<% end %>